# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lda_online_cpp <- function(doc_ids, terms, counts, K, K0, passes, batchsize, maxiter, tau_0, kappa, eta, alpha, refLambda) {
    .Call(`_RefTM_lda_online_cpp`, doc_ids, terms, counts, K, K0, passes, batchsize, maxiter, tau_0, kappa, eta, alpha, refLambda)
}

